name = "scam-detector"
main = "src/index.ts"
compatibility_date = "2024-03-04"

[vars]
## Algod
ALGO_INDEXER_SERVER="https://mainnet-idx.algonode.cloud"

## Chaintrail
CHAINTRAIL_BLACKLIST_URL="https://chaintrail.io/api/v1/scam/blacklist"